class CategoriesService {
    static getAllCategories() {

        return [
            {
                code: 1,
                title: 'Food',
                theme: 'Food & Drinks',
                words: [
                    "pizza",
                    "pasta",
                    "burger",
                    "sushi",
                    "taco",
                    "salad",
                    "sandwich",
                    "smoothie",
                    "coffee",
                    "tea",
                    "juice",
                    "cake",
                    "cookie",
                    "ice cream",
                    "steak",
                    "chicken",
                    "soup",
                    "noodles",
                    "pancake",
                    "bacon",
                    "sausage",
                    "cheese",
                    "wine",
                    "beer",
                    "cocktail",
                    "lemonade",
                    "popcorn",
                    "chocolate",
                    "apple",
                    "banana",
                    "strawberry",
                    "blueberry",
                    "watermelon",
                    "orange",
                    "Burrito",
                    "Korian BBQ",
                    "Sushi",
                    "Ramen",
                    "Cotage Pie",
                    "Fish and Chips",
                    "Vegemite",
                    "Pavlova",
                    "Meat Pie",
                    "Fairy Bread",
                    "Pumpkin Soup",

                ]
            },
            {
                code: 2,
                title: 'Places',
                theme: 'Famous Places',
                words: [
                    "Eiffel Tower",
                    "Statue of Liberty",
                    "Taj Mahal",
                    "Great Wall of China",
                    "Pyramids of Giza",
                    "Machu Picchu",
                    "Colosseum",
                    "Niagara Falls",
                    "Santorini",
                    "Venice",
                    "Grand Canyon",
                    "Sydney Opera House",
                    "Petra",
                    "Mount Everest",
                    "Yellowstone National Park",
                    "Acropolis of Athens",
                    "Stonehenge",
                    "Mount Fuji",
                    "The Louvre",
                    "Times Square",
                    "Red Square",
                    "Mount Rushmore",
                    "Neuschwanstein Castle",
                    "Alhambra",
                    "Dubai Marina",
                    "Chichen Itza",
                    "Burj Khalifa",
                    "Mall of America",
                    "Hollywood Sign",
                    "Golden Gate Bridge",
                    "Las Vegas",
                    "Disneyland",
                    "Hawaii",
                    "Miami",
                    "New York City",
                    "Los Angeles",
                    "San Francisco",
                    "Angkor Wat, Cambodia",
                    "Easter Island",
                    "Tower of Pisa",
                    "Niagra Falls",
                    "Amazon Rainforest",
                    "Christ the Redeemer",
                    "The Colosseum",
                    "Mount Fuji",
                    "Uyuni Salt Flats",
                ]
            },
            {
                code: 4,
                title: 'Countries',
                theme: 'Countries',
                words: [
                    [
                        "Afghanistan",
                        "Albania",
                        "Algeria",
                        "Andorra",
                        "Angola",
                        "Antigua and Barbuda",
                        "Argentina",
                        "Armenia",
                        "Australia",
                        "Austria",
                        "Azerbaijan",
                        "Bahamas",
                        "Bahrain",
                        "Bangladesh",
                        "Barbados",
                        "Belarus",
                        "Belgium",
                        "Belize",
                        "Benin",
                        "Bhutan",
                        "Bolivia",
                        "Bosnia and Herzegovina",
                        "Botswana",
                        "Brazil",
                        "Brunei",
                        "Bulgaria",
                        "Burkina Faso",
                        "Burundi",
                        "Cabo Verde",
                        "Cambodia",
                        "Cameroon",
                        "Canada",
                        "Central African Republic",
                        "Chad",
                        "Chile",
                        "China",
                        "Colombia",
                        "Comoros",
                        "Congo",
                        "Costa Rica",
                        "Croatia",
                        "Cuba",
                        "Cyprus",
                        "Czech Republic",
                        "Denmark",
                        "Djibouti",
                        "Dominica",
                        "Dominican Republic",
                        "East Timor",
                        "Ecuador",
                        "Egypt",
                        "El Salvador",
                        "Equatorial Guinea",
                        "Eritrea",
                        "Estonia",
                        "Eswatini",
                        "Ethiopia",
                        "Fiji",
                        "Finland",
                        "France",
                        "Gabon",
                        "Gambia",
                        "Georgia",
                        "Germany",
                        "Ghana",
                        "Greece",
                        "Grenada",
                        "Guatemala",
                        "Guinea",
                        "Guinea-Bissau",
                        "Guyana",
                        "Haiti",
                        "Honduras",
                        "Hungary",
                        "Iceland",
                        "India",
                        "Indonesia",
                        "Iran",
                        "Iraq",
                        "Ireland",
                        "Israel",
                        "Italy",
                        "Jamaica",
                        "Japan",
                        "Jordan",
                        "Kazakhstan",
                        "Kenya",
                        "Kiribati",
                        "Korea, North",
                        "Korea, South",
                        "Kosovo",
                        "Kuwait",
                        "Kyrgyzstan",
                        "Laos",
                        "Latvia",
                        "Lebanon",
                        "Lesotho",
                        "Liberia",
                        "Libya",
                        "Liechtenstein",
                        "Lithuania",
                        "Luxembourg",
                        "Madagascar",
                        "Malawi",
                        "Malaysia",
                        "Maldives",
                        "Mali",
                        "Malta",
                        "Marshall Islands",
                        "Mauritania",
                        "Mauritius",
                        "Mexico",
                        "Micronesia",
                        "Moldova",
                        "Monaco",
                        "Mongolia",
                        "Montenegro",
                        "Morocco",
                        "Mozambique",
                        "Myanmar",
                        "Namibia",
                        "Nauru",
                        "Nepal",
                        "Netherlands",
                        "New Zealand",
                        "Nicaragua",
                        "Niger",
                        "Nigeria",
                        "North Macedonia",
                        "Norway",
                        "Oman",
                        "Pakistan",
                        "Palau",
                        "Panama",
                        "Papua New Guinea",
                        "Paraguay",
                        "Peru",
                        "Philippines",
                        "Poland",
                        "Portugal",
                        "Qatar",
                        "Romania",
                        "Russia",
                        "Rwanda",
                        "Saint Kitts and Nevis",
                        "Saint Lucia",
                        "Saint Vincent and the Grenadines",
                        "Samoa",
                        "San Marino",
                        "Sao Tome and Principe",
                        "Saudi Arabia",
                        "Senegal",
                        "Serbia",
                        "Seychelles",
                        "Sierra Leone",
                        "Singapore",
                        "Slovakia",
                        "Slovenia",
                        "Solomon Islands",
                        "Somalia",
                        "South Africa",
                        "South Sudan",
                        "Spain",
                        "Sri Lanka",
                        "Sudan",
                        "Suriname",
                        "Sweden",
                        "Switzerland",
                        "Syria",
                        "Taiwan",
                        "Tajikistan",
                        "Tanzania",
                        "Thailand",
                        "Togo",
                        "Tonga",
                        "Trinidad and Tobago",
                        "Tunisia",
                        "Turkey",
                        "Turkmenistan",
                        "Tuvalu",
                        "Uganda",
                        "Ukraine",
                        "United Arab Emirates",
                        "United Kingdom",
                        "United States",
                        "Uruguay",
                        "Uzbekistan",
                        "Vanuatu",
                        "Vatican City",
                        "Venezuela",
                        "Vietnam",
                        "Yemen",
                        "Zambia",
                        "Zimbabwe"
                    ]
                ]
            },
            {
                code: 5,
                title: 'Movies',
                theme: 'Movies',
                words: [
                    "The Shawshank Redemption",
                    "The Godfather",
                    "Pulp Fiction",
                    "Forrest Gump",
                    "The Matrix",
                    "Inception",
                    "Titanic",
                    "Avatar",
                    "Jurassic Park",
                    "The Lord of the Rings",
                    "Star Wars",
                    "Back to the Future",
                    "Gladiator",
                    "The Dark Knight",
                    "The Avengers",
                    "The Silence of the Lambs",
                    "Fight Club",
                    "The Lion King",
                    "E.T. the Extra-Terrestrial",
                    "Frozen",
                    "Harry Potter and the Sorcerer's Stone",
                    "Casablanca",
                    "Gone with the Wind",
                    "Braveheart",
                    "The Shawshank Redemption",
                    "Goodfellas",
                    "Schindler's List",
                    "The Green Mile",
                    "The Shawshank Redemption",
                    "The Godfather",
                    "Pulp Fiction",
                    "Forrest Gump",
                    "The Matrix",
                    "Inception",
                    "Titanic",
                    "Avatar",
                    "Jurassic Park",
                    "The Lord of the Rings",
                    "Star Wars",
                    "Back to the Future",
                    "Gladiator",
                    "The Dark Knight",
                    "The Avengers",
                    "Interstellar",
                    "Fight Club",
                    "The Lion King",
                    "E.T. the Extra-Terrestrial",
                    "Frozen",
                    "Harry Potter and the Sorcerer's Stone",
                    "Casablanca",
                    "Gone with the Wind",
                    "Braveheart",
                    "Goodfellas",
                    "Schindler's List",
                    "The Green Mile",
                    "The Departed",
                    "Inglourious Basterds",
                    "The Shawshank Redemption",
                    "The Godfather: Part II",
                    "The Prestige",
                    "The Usual Suspects",
                    "The Sixth Sense",
                    "The Social Network",
                    "The Grand Budapest Hotel",
                    "La La Land",
                    "The Revenant",
                    "The Witch",
                    "Mad Max: Fury Road",
                    "The Shape of Water",
                    "Moonlight",
                    "Arrival",
                    "Blade Runner 2049",
                    "Get Out",
                    "The Handmaiden",
                    "Parasite",
                    "The Irishman"
                ]
            },
            {
                code: 6,
                title: 'Disney',
                theme: 'Disney personalities',
                words: [
                    "Mickey Mouse",
                    "Minnie Mouse",
                    "Donald Duck",
                    "Goofy",
                    "Pluto",
                    "Cinderella",
                    "Snow White",
                    "Ariel",
                    "Belle",
                    "Jasmine",
                    "Simba",
                    "Mufasa",
                    "Scar",
                    "Nemo",
                    "Dory",
                    "Buzz Lightyear",
                    "Woody",
                    "Elsa",
                    "Anna",
                    "Olaf",
                    "Mulan",
                    "Pocahontas",
                    "Tiana",
                    "Rapunzel",
                    "Merida",
                    "Aladdin",
                    "Genie",
                    "Tinker Bell",
                    "Winnie the Pooh",
                    "Tigger",
                    "Eeyore",
                    "Piglet",
                    "Rabbit",
                    "Christopher Robin",
                    "Peter Pan",
                    "Captain Hook",
                    "Tinker Bell",
                    "Aurora",
                    "Maleficent",
                    "Beast",
                    "Belle",
                    "Gaston",
                    "Ariel",
                    "Ursula",
                    "Jasmine",
                    "Aladdin",
                    "Jafar",
                    "Harry Potter",
                    "Hermione Granger",
                    "Ron Weasley",
                    "Dumbledore",
                    "Voldemort",
                    "Hagrid",
                    "Snape",
                    "Sirius Black",
                    "Luna Lovegood",
                    "Neville Longbottom",
                    "Simpisons",
                    "Homer Simpisons",
                    "Marge Simpisons",
                    "Bart Simpisons",
                    "Lisa Simpisons",
                    "Maggie Simpisons",
                    "Mr. Burns (Simpisons) ",
                    "Ned Flanders (Simpisons)",                    
                    
                ]
            },
            {
                code: 7,
                title: 'Professions',
                theme: 'Professions',
                words: [
                    "Doctor",
                    "Engineer",
                    "Teacher",
                    "Artist",
                    "Chef",
                    "Police Officer",
                    "Firefighter",
                    "Pilot",
                    "Actor",
                    "Musician",
                    "Writer",
                    "Photographer",
                    "Athlete",
                    "Architect",
                    "Lawyer",
                    "Entrepreneur",
                    "Scientist",
                    "Veterinarian",
                    "Electrician",
                    "Plumber",
                    "Dentist",
                    "Nurse",
                    "Farmer",
                    "Mechanic",
                    "Banker",
                    "Barista",
                    "Fashion Designer",
                    "Psychologist",
                    "Social Worker",
                    "Journalist",
                    "Librarian",
                    "Politician",
                    "Soldier",
                    "Astronaut",
                    "Magician",
                    "Baker",
                    "Butcher",
                    "Carpenter",
                    "Construction Worker",
                    "Dancer",
                    "Flight Attendant",
                    "Interior Designer",
                    "Model",
                    "Painter",
                    "Singer",
                    "Waiter",
                    "Zookeeper",
                    "Coach",
                    "Electrician",
                    "Plumber",
                    "Dentist",
                    "Nurse",
                    "Farmer",
                    "Mechanic",
                    "Fake News Maker",

                ]
            },
            {
                code: 8,
                title: 'Animals',
                theme: 'Animals',
                words: [
                    "Dog",
                    "Cat",
                    "Elephant",
                    "Lion",
                    "Tiger",
                    "Giraffe",
                    "Monkey",
                    "Dolphin",
                    "Whale",
                    "Penguin",
                    "Kangaroo",
                    "Panda",
                    "Zebra",
                    "Horse",
                    "Bird",
                    "Fish",
                    "Snake",
                    "Turtle",
                    "Frog",
                    "Butterfly",
                    "Owl",
                    "Squirrel",
                    "Bear",
                    "Wolf",
                    "Fox",
                    "Rabbit",
                    "Deer",
                    "Eagle",
                    "Crocodile",
                    "Shark",
                    "Octopus",
                    "Seahorse",
                    "Jellyfish",
                    "Starfish",
                    "Crab",
                    "Lobster",
                    "Shrimp",
                    "Pig",
                    "Cow",
                    "Chicken",
                    "Sheep",
                    "Goat",
                    "Duck",
                    "Turkey",
                    "Hedgehog",
                    "Raccoon",
                    "Otter",
                    "Beaver",
                    "Hamster",
                    "Guinea Pig",
                    "Parrot",
                    "Goldfish",


                ]
            },
            {
                code: 9,
                title: 'Objects',
                theme: 'Objects and Things',
                words: [
                    "Chair",
                    "Table",
                    "Lamp",
                    "Computer",
                    "Phone",
                    "Book",
                    "Camera",
                    "Car",
                    "Bicycle",
                    "Watch",
                    "Glasses",
                    "Shoes",
                    "Wallet",
                    "Pen",
                    "Notebook",
                    "Knife",
                    "Fork",
                    "Plate",
                    "Cup",
                    "Spoon",
                    "Brush",
                    "Mirror",
                    "Clock",
                    "Keys",
                    "Door",
                    "Window",
                    "Remote",
                    "Headphones",
                    "Backpack",
                    "Umbrella",
                    "Guitar",
                    "Microphone",
                    "Drums",
                    "Microscope",
                    "Microwave",
                    "Speaker",
                    "Television",
                    "Laundry Machine",
                    "Ladder",
                    "Hammer",
                    "Nail",
                    "Screwdriver",
                    "Saw",
                    "Photo Frame",
                    "Candle",
                    "Vase",
                    "Flower",
                ]
            },

            {
                code: 10,
                title: 'TV Shows',
                theme: 'TV Shows',
                words: [
                    "Game of Thrones",
                    "Breaking Bad",
                    "Stranger Things",
                    "Friends",
                    "The Office",
                    "Sherlock",
                    "The Crown",
                    "The Mandalorian",
                    "Black Mirror",
                    "Westworld",
                    "The Simpsons",
                    "Rick and Morty",
                    "The Walking Dead",
                    "Mindhunter",
                    "Fargo",
                    "Lost",
                    "The Big Bang Theory",
                    "Peaky Blinders",
                    "Narcos",
                    "The Handmaid's Tale",
                    "Better Call Saul",
                    "House of Cards",
                    "Downton Abbey",
                    "Chernobyl",
                    "The Witcher",
                    "Stranger Things",
                    "True Detective",
                    "The Marvelous Mrs. Maisel",
                    "Brooklyn Nine-Nine",
                    "Archer",
                    "Homeland",
                    "This Is Us",
                    "The Good Place",
                    "BoJack Horseman",
                    "Money Heist",
                    "The Boys",
                    "The Expanse",
                    "The Haunting of Hill House",
                    "Outlander",
                    "Dark",
                    "Ozark",
                    "The Umbrella Academy",
                    "Cobra Kai",
                    "Altered Carbon",
                    "The Mandalorian",
                    "The Witcher",
                    "Every Body Hate Chris",
                    "The Fresh Prince of Bel-Air",
                    "The Nanny",
                    "The Golden"
                ]
            },
            {
                code: 11,
                title: 'Famous People',
                theme: 'Famous People',
                words: [
                    "Albert Einstein",
                    "Leonardo da Vinci",
                    "Martin Luther King Jr.",
                    "Nelson Mandela",
                    "Mahatma Gandhi",
                    "Abraham Lincoln",
                    "Steve Jobs",
                    "Elon Musk",
                    "Oprah Winfrey",
                    "Michael Jordan",
                    "Serena Williams",
                    "David Beckham",
                    "Beyoncé",
                    "Taylor Swift",
                    "Marilyn Monroe",
                    "Leonardo DiCaprio",
                    "Tom Hanks",
                    "Angelina Jolie",
                    "Emma Watson",
                    "Kanye West",
                    "Ellen DeGeneres",
                    "Stephen Hawking",
                    "J.K. Rowling",
                    "Barack Obama",
                    "Queen Elizabeth II",
                    "Winston Churchill",
                    "Pablo Picasso",
                    "Vincent van Gogh",
                    "Amelia Earhart",
                    "Muhammad Ali",
                    "Pele",
                    "Marie Curie",
                    "Bill Gates",
                    "Mark Zuckerberg",
                    "Malala Yousafzai",
                    "Rosa Parks",
                    "Walt Disney",
                    "Steve Irwin",
                    "Princess Diana",
                    "Alexander Graham Bell",
                    "Coco Chanel",
                    "Ernest Hemingway",
                    "Frida Kahlo",
                    "Neil Armstrong",
                    "Elvis Presley",
                    "Bob Marley",
                    "Michael Jackson",
                    "John Lennon",
                    "Freddie Mercury",

                ]
            },
            {
                code: 12,
                title: 'Video Games',
                theme: 'Video Games',
                words: [
                    "The Legend of Zelda",
                    "Super Mario Bros.",
                    "Pokémon",
                    "Final Fantasy",
                    "Halo",
                    "Call of Duty",
                    "Fortnite",
                    "Minecraft",
                    "Grand Theft Auto",
                    "Overwatch",
                    "League of Legends",
                    "World of Warcraft",
                    "The Elder Scrolls",
                    "Metal Gear Solid",
                    "Uncharted",
                    "Resident Evil",
                    "Assassin's Creed",
                    "Super Smash Bros.",
                    "Fallout",
                    "Red Dead Redemption",
                    "Dark Souls",
                    "The Witcher",
                    "God of War",
                    "Destiny",
                    "Street Fighter",
                    "Mortal Kombat",
                    "FIFA",
                    "NBA 2K",
                    "Animal Crossing",
                    "Splatoon",
                    "Doom",
                    "Counter-Strike",
                    "Half-Life",
                    "The Sims",
                    "Diablo",
                    "StarCraft",
                    "Borderlands",
                    "Portal",
                    "Mass Effect",
                    "Rocket League",
                    "Fortnite",
                    "Among Us",
                    "Cyberpunk 2077",
                    "Valorant",
                    "Apex Legends",
                    "Genshin Impact",
                    "The Last of Us",
                    "Mario Kart",
                    "Donkey Kong",
                    "Bomberman",
                    "Sonic the Hedgehog",
                ]
            },
            {
                code: 13,
                title: 'Pokemons',
                theme: 'Pokemons',
                words: [
                    "Pikachu",
                    "Charizard",
                    "Bulbasaur",
                    "Squirtle",
                    "Jigglypuff",
                    "Mewtwo",
                    "Eevee",
                    "Snorlax",
                    "Gyarados",
                    "Dragonite",
                    "Mew",
                    "Gengar",
                    "Magikarp",
                    "Psyduck",
                    "Vaporeon",
                    "Flareon",
                    "Jolteon",
                    "Gardevoir",
                    "Lucario",
                    "Lugia",
                    "Ho-Oh",
                    "Rayquaza",
                    "Groudon",
                    "Kyogre",
                    "Celebi",
                    "Greninja",
                    "Charmander",
                    "Blastoise",
                    "Venusaur",
                    "Raichu",
                    "Zapdos",
                    "Articuno",
                    "Moltres",
                    "Suicune",
                    "Entei",
                    "Raikou",
                    "Lapras",
                    "Gengar",
                    "Alakazam",
                    "Arcanine",
                    "Pidgeot",
                    "Sceptile",
                    "Gardevoir",
                    "Swampert",
                    "Blaziken",
                    "Gallade",
                    "Garchomp"
                ]
            },
            {
                code: 14,
                title: 'Brazilians',
                theme: 'Bagulhos do Brasil',
                words: [
                    "Samba",
                    "Carnaval",
                    "Rio de Janeiro",
                    "São Paulo",
                    "Brasília",
                    "Ipanema",
                    "Capoeira",
                    "Feijoada",
                    "Açaí",
                    "Caipirinha",
                    "Pelé",
                    "Ronaldinho",
                    "Neymar",
                    "Gisele Bündchen",
                    "Oscar Niemeyer",
                    "Cristo Redentor",
                    "Fernando de Noronha",
                    "Pantanal",
                    "Favela",
                    "Tropicalismo",
                    "Jorge Amado",
                    "Vinicius de Moraes",
                    "Tom Jobim",
                    "Gilberto Gil",
                    "Carmen Miranda",
                    "Churrasco",
                    "Bossa Nova",
                    "Cangaço",
                    "Telenovela",
                    "Cachaça",
                    "Maracanã",
                    "Paraty",
                    "Porto de Galinhas",
                    "Salvador",
                    "Ouro Preto",
                    "Tiradentes",
                    "Recife",
                    "Bahia",
                    "Pão de Açúcar",
                    "Copacabana",
                    "Anitta",
                    "Jair Bolsonaro",
                    "Ayrton Senna",
                    "Gabriela Mistral",
                    "Carlos Drummond de Andrade",
                    "Machado de Assis",
                    "Clarice Lispector",
                    "Tarsila do Amaral",
                    "Oswald de Andrade",
                    "Heitor Villa-Lobos",
                    "Carmen Miranda",
                    "Chico Buarque",
                    "Caetano Veloso",
                    "Dilma Rousseff",
                    "Fernando Henrique Cardoso",
                    "Luiz Inácio Lula da Silva",
                    "Jair Bolsonaro",
                    "Cunbica",
                    "Carnaval",
                    "Mula Sem Cabeça",
                    "Boitatá",
                    "Sapo Cururu",
                    "Curupira",
                    "Dedo no Cu e Gritaria",
                    "Pau de Selfie",
                    "Pão de Queijo",
                    "Coxinha",
                    "Brigadeiro",
                    "Pão na Chapa",
                    "Pastel de Feira",
                    "Cachorro Caramelo",
                    "Cantor de Funk",
                    "Cantor Ventania",
                    "Rei Pele",
                    "Turma da Mônica",
                    "Cavaquinho",


                ]
            },
            {
                code: 15,
                title: 'Brazilian Movies/TV',
                theme: 'Brazilian Movies/TV',
                words: [
                    "Cidade de Deus",
                    "Central do Brasil",
                    "Tropa de Elite",
                    "Dois Papas",
                    "Bacurau",
                    "Aquarius",
                    "Diários de Motocicleta",
                    "Avenida Brasil",
                    "O Mecanismo",
                    "A Mulher Invisível",
                    "O Palhaço",
                    "Meu Amigo Hindu",
                    "O Beijo da Mulher Aranha",
                    "FO Que É Isso, Companheiro?",
                    "Viva Voz",
                    "Paraíso Tropical",
                    "Eu, Tu, Eles",
                    "O Ano em Que Meus Pais Saíram de Férias",
                    "Os Inquilinos",
                    "Aquarius",
                    "Que Horas Ela Volta?",
                    "GBom Dia, Verônica",
                    "Cidade Baixa",
                    "Carandiru",
                    "O Rei do Gado",
                    "O Clone",
                    "Fogo no Céu",
                    "Favela Rising",
                    "A Mulher Invisível",
                    "Trash: A Esperança Vem do Lixo",
                    "O Homem do Futuro",
                    "Relatos Selvagens",
                    "Narcos",
                    "Democracia em Vertigem",
                    "Coisa Mais Linda",
                    "Chaves",
                    "Carrossel",
                    "A Grande Família",
                    "Sítio do Picapau Amarelo",
                    "Casseta & Planeta",
                    "Os Normais",
                    "Castelo Rá-Tim-Bum",
                    "A Diarista",
                    "Chapolin Colorado",
                    "TV Colosso",
                    "Xuxa",
                    "Globo Repórter",
                    "Fantástico",
                    "Pequenas Empresas, Grandes Negócios",
                    "Rebeldez",
                    "BBB",


                ]
            },
            {
                code: 16,
                title: "Sports",
                theme: "Sports",
                words: [
                    "Soccer",
                    "Basketball",
                    "Tennis",
                    "Golf",
                    "Swimming",
                    "Running",
                    "Boxing",
                    "Martial Arts",
                    "Cricket",
                    "Baseball",
                    "Ice Hockey",
                    "Cycling",
                    "Rugby",
                    "Gymnastics",
                    "Wrestling",
                    "Surfing",
                    "Skiing",
                    "Snowboarding",
                    "Volleyball",
                    "Badminton"
                ]
            },
            {
                code: 17,
                title: "Technology",
                theme: "Technology",
                words: [
                    "Computer",
                    "Smartphone",
                    "Tablet",
                    "Laptop",
                    "Internet",
                    "Software",
                    "Hardware",
                    "Artificial Intelligence",
                    "Virtual Reality",
                    "Augmented Reality",
                    "Robotics",
                    "Blockchain",
                    "Cybersecurity",
                    "Cloud Computing",
                    "Biotechnology",
                    "Drones",
                    "IoT (Internet of Things)",
                    "Machine Learning",
                    "3D Printing",
                    "Space Exploration"
                ]
            },
            {
                code: 18,
                title: "Music Genres",
                theme: "Music Genres",
                words: [
                    "Pop",
                    "Rock",
                    "Hip Hop",
                    "Jazz",
                    "Blues",
                    "Country",
                    "Classical",
                    "Electronic",
                    "Reggae",
                    "R&B",
                    "Folk",
                    "Metal",
                    "Punk",
                    "Salsa",
                    "K-Pop",
                    "EDM",
                    "Funk",
                    "Gospel",
                    "Indie",
                    "Opera"
                ]
            },
            {
                code: 19,
                title: "Colors",
                theme: "Colors",
                words: [
                    "Red",
                    "Blue",
                    "Green",
                    "Yellow",
                    "Orange",
                    "Purple",
                    "Pink",
                    "Black",
                    "White",
                    "Brown",
                    "Gray",
                    "Silver",
                    "Gold",
                    "Turquoise",
                    "Crimson",
                    "Magenta",
                    "Indigo",
                    "Lime",
                    "Maroon",
                    "Teal"
                ]
            },

        ];
    }

    static getSelectedCategories() {

        if (typeof window === 'undefined') return [];

        const selectedCategories = JSON.parse(localStorage.getItem('selected-categories')) || [];
        const allCategories = CategoriesService.getAllCategories();
        const selectedCategoriesData = [];

        for (let i = 0; i < selectedCategories.length; i++) {
            const categoryCode = selectedCategories[i];
            const categoryData = allCategories.find(category => category.code === categoryCode);
            if (categoryData) {
                selectedCategoriesData.push(categoryData);
            }
        }

        if (localStorage.getItem('custom-category-selected') === 'true') {
            if (localStorage.getItem('custom-category-words') !== null && localStorage.getItem('custom-category-title') !== null) {
                selectedCategoriesData.push({
                    code: 999,
                    title: localStorage.getItem('custom-category-title') || 'Custom Category',
                    theme: localStorage.getItem('custom-category-title') || 'Custom Category',
                    words: JSON.parse(localStorage.getItem('custom-category-words')) || [""]
                });
            }
        }
        return selectedCategoriesData;
    }
}

export default CategoriesService;