class CategoriesService {
    static getAllCategories() {
        return [
            {
                code: 1,
                title: 'Food',
                theme: 'Food & Drinks',
                words: [
                    "pizza",
                    "pasta",
                    "burger",
                    "sushi",
                    "taco",
                    "salad",
                    "sandwich",
                    "smoothie",
                    "coffee",
                    "tea",
                    "juice",
                    "cake",
                    "cookie",
                    "ice cream",
                    "steak",
                    "chicken",
                    "soup",
                    "noodles",
                    "pancake",
                    "bacon",
                    "sausage",
                    "cheese",
                    "wine",
                    "beer",
                    "cocktail",
                    "lemonade",
                    "popcorn",
                    "chocolate",
                    "apple",
                    "banana",
                    "strawberry",
                    "blueberry",
                    "watermelon",
                    "orange",

                    
                ]
            },
            {
                code: 2,
                title: 'Places',
                theme: 'Famous Places',
                words: [
                    "Eiffel Tower",
                    "Statue of Liberty",
                    "Taj Mahal",
                    "Great Wall of China",
                    "Pyramids of Giza",
                    "Machu Picchu",
                    "Colosseum",
                    "Niagara Falls",
                    "Santorini",
                    "Venice",
                    "Grand Canyon",
                    "Sydney Opera House",
                    "Petra",
                    "Mount Everest",
                    "Yellowstone National Park",
                    "Acropolis of Athens",
                    "Stonehenge",
                    "Mount Fuji",
                    "The Louvre",
                    "Times Square",
                    "Red Square",
                    "Mount Rushmore",
                    "Neuschwanstein Castle",
                    "Alhambra",
                    "Dubai Marina",
                    "Chichen Itza",
                    "Burj Khalifa",
                    "Mall of America",
                    "Hollywood Sign",
                    "Golden Gate Bridge"
                ]
            },
            {
                code: 4,
                title: 'Countries',
                theme: 'Countries',
                words: [
                    "United States",
                    "Canada",
                    "Mexico",
                    "Brazil",
                    "Argentina",
                    "United Kingdom",
                    "France",
                    "Germany",
                    "Italy",
                    "Spain",
                    "Russia",
                    "China",
                    "Japan",
                    "India",
                    "Australia",
                    "South Africa",
                    "Egypt",
                    "Kenya",
                    "Nigeria",
                    "Saudi Arabia",
                    "United Arab Emirates",
                    "Turkey",
                    "Greece",
                    "Thailand",
                    "Vietnam",
                    "South Korea",
                    "New Zealand",
                    "Switzerland",
                    "Norway",
                    "Sweden"
                ]
            },
            {
                code: 5,
                title: 'Movies',
                theme: 'Movies',
                words: [
                    "The Shawshank Redemption",
                    "The Godfather",
                    "Pulp Fiction",
                    "Forrest Gump",
                    "The Matrix",
                    "Inception",
                    "Titanic",
                    "Avatar",
                    "Jurassic Park",
                    "The Lord of the Rings",
                    "Star Wars",
                    "Back to the Future",
                    "Gladiator",
                    "The Dark Knight",
                    "The Avengers",                    
                    "The Silence of the Lambs",
                    "Fight Club",
                    "The Lion King",
                    "E.T. the Extra-Terrestrial",
                    "Frozen",
                    "Harry Potter and the Sorcerer's Stone",
                    "Casablanca",
                    "Gone with the Wind",
                    "Braveheart",
                    "The Shawshank Redemption",
                    "Goodfellas",
                    "Schindler's List",
                    "The Green Mile",                    
                    "The Shawshank Redemption",
                    "The Godfather",
                    "Pulp Fiction",
                    "Forrest Gump",
                    "The Matrix",
                    "Inception",
                    "Titanic",
                    "Avatar",
                    "Jurassic Park",
                    "The Lord of the Rings",
                    "Star Wars",
                    "Back to the Future",
                    "Gladiator",
                    "The Dark Knight",
                    "The Avengers",
                    "Interstellar",
                    
                    "Fight Club",
                    "The Lion King",
                    "E.T. the Extra-Terrestrial",
                    "Frozen",
                    "Harry Potter and the Sorcerer's Stone",
                    "Casablanca",
                    "Gone with the Wind",
                    "Braveheart",
                    "Goodfellas",
                    "Schindler's List",
                    "The Green Mile",
                    "The Departed",
                    "Inglourious Basterds",
                    "The Shawshank Redemption",
                    "The Godfather: Part II",
                    "The Prestige",
                    "The Usual Suspects",
                    "The Sixth Sense",
                    "The Social Network",
                    "The Grand Budapest Hotel",
                    "La La Land",
                    "The Revenant",
                    "The Witch",
                    "Mad Max: Fury Road",
                    "The Shape of Water",
                    "Moonlight",
                    "Arrival",
                    "Blade Runner 2049",
                    "Get Out",
                    "The Handmaiden",
                    "Parasite",
                    "The Irishman"
                ]
            },
            {
                code: 6,
                title: 'Disney',
                theme: 'Disney personalities',
                words: [
                    "Mickey Mouse",
                    "Minnie Mouse",
                    "Donald Duck",
                    "Goofy",
                    "Pluto",
                    "Cinderella",
                    "Snow White",
                    "Ariel",
                    "Belle",
                    "Jasmine",
                    "Simba",
                    "Mufasa",
                    "Scar",
                    "Nemo",
                    "Dory",
                    "Buzz Lightyear",
                    "Woody",
                    "Elsa",
                    "Anna",
                    "Olaf",
                    "Mulan",
                    "Pocahontas",
                    "Tiana",
                    "Rapunzel",
                    "Merida",
                    "Aladdin",
                    "Genie",
                    "Tinker Bell",
                    "Winnie the Pooh",
                    "Tigger",
                    "Eeyore",
                    "Piglet",
                    "Rabbit",
                    "Christopher Robin",
                    "Peter Pan",
                    "Captain Hook",
                    "Tinker Bell",
                    "Aurora",
                    "Maleficent",
                    "Beast",
                    "Belle",
                    "Gaston",
                    "Ariel",
                    "Ursula",
                    "Jasmine",
                    "Aladdin",
                    "Jafar",
                    "Harry Potter",
                    "Hermione Granger",
                    "Ron Weasley",
                    "Dumbledore",
                    "Voldemort",
                    "Hagrid",
                    "Snape",
                    "Sirius Black",
                    "Luna Lovegood",
                    "Neville Longbottom",
                    "Simpisons",
                    "Homer Simpisons",
                    "Marge Simpisons",
                    "Bart Simpisons",
                    "Lisa Simpisons",
                    "Maggie Simpisons",
                    "Mr. Burns (Simpisons) ",
                    "Ned Flanders (Simpisons)",

                    
                    


                ]
            },
            {
                code: 7,
                title: 'Professions',
                theme: 'Professions',
                words: [
                    "Doctor",
                    "Engineer",
                    "Teacher",
                    "Artist",
                    "Chef",
                    "Police Officer",
                    "Firefighter",
                    "Pilot",
                    "Actor",
                    "Musician",
                    "Writer",
                    "Photographer",
                    "Athlete",
                    "Architect",
                    "Lawyer",
                    "Entrepreneur",
                    "Scientist",
                    "Veterinarian",
                    "Electrician",
                    "Plumber",
                    "Dentist",
                    "Nurse",
                    "Farmer",
                    "Mechanic",
                    "Banker",
                    "Barista",
                    "Fashion Designer",
                    "Psychologist",
                    "Social Worker",
                    "Journalist",
                    "Librarian",
                    "Politician",
                    "Soldier",
                    "Astronaut",
                    "Magician",
                    "Baker",
                    "Butcher",
                    "Carpenter",
                    "Construction Worker",
                    "Dancer",
                    "Flight Attendant",
                    "Interior Designer",
                    "Model",
                    "Painter",
                    "Singer",
                    "Waiter",
                    "Zookeeper",
                    "Coach",
                    "Electrician",
                    "Plumber",
                    "Dentist",
                    "Nurse",
                    "Farmer",
                    "Mechanic",
                    "Fake News Maker",

                ]
            },
            {
                code: 8,
                title: 'Animals',
                theme: 'Animals',
                words: [
                    "Dog",
                    "Cat",
                    "Elephant",
                    "Lion",
                    "Tiger",
                    "Giraffe",
                    "Monkey",
                    "Dolphin",
                    "Whale",
                    "Penguin",
                    "Kangaroo",
                    "Panda",
                    "Zebra",
                    "Horse",
                    "Bird",
                    "Fish",
                    "Snake",
                    "Turtle",
                    "Frog",
                    "Butterfly",
                    "Owl",
                    "Squirrel",
                    "Bear",
                    "Wolf",
                    "Fox",
                    "Rabbit",
                    "Deer",
                    "Eagle",
                    "Crocodile",
                    "Shark",
                    "Octopus",
                    "Seahorse",
                    "Jellyfish",
                    "Starfish",
                    "Crab",
                    "Lobster",
                    "Shrimp",
                    "Pig",
                    "Cow",
                    "Chicken",
                    "Sheep",
                    "Goat",
                    "Duck",
                    "Turkey",
                    "Hedgehog",
                    "Raccoon",
                    "Otter",
                    "Beaver",
                    "Hamster",
                    "Guinea Pig",
                    "Parrot",                    
                    "Goldfish",
                    

                ]
            },
            {
                code: 9,
                title: 'Objects',
                theme: 'Objects and Things',
                words: [
                    "Chair",
                    "Table",
                    "Lamp",
                    "Computer",
                    "Phone",
                    "Book",
                    "Camera",
                    "Car",
                    "Bicycle",
                    "Watch",
                    "Glasses",
                    "Shoes",
                    "Wallet",
                    "Pen",
                    "Notebook",
                    "Knife",
                    "Fork",
                    "Plate",
                    "Cup",
                    "Spoon",
                    "Brush",
                    "Mirror",
                    "Clock",
                    "Keys",
                    "Door",
                    "Window",
                    "Remote",
                    "Headphones",
                    "Backpack",
                    "Umbrella",
                    "Guitar",
                    "Microphone",
                    
                ]
            },
            
            {
                code: 10,
                title: 'TV Shows',
                theme: 'TV Shows',
                words: [
                    "Game of Thrones",
                    "Breaking Bad",
                    "Stranger Things",
                    "Friends",
                    "The Office",
                    "Sherlock",
                    "The Crown",
                    "The Mandalorian",
                    "Black Mirror",
                    "Westworld",
                    "The Simpsons",
                    "Rick and Morty",
                    "The Walking Dead",
                    "Mindhunter",
                    "Fargo",
                    "Lost",
                    "The Big Bang Theory",
                    "Peaky Blinders",
                    "Narcos",
                    "The Handmaid's Tale",
                    "Better Call Saul",
                    "House of Cards",
                    "Downton Abbey",
                    "Chernobyl",
                    "The Witcher",
                    "Stranger Things",
                    "True Detective",
                    "The Marvelous Mrs. Maisel",
                    "Brooklyn Nine-Nine",
                    "Archer",
                    "Homeland",
                    "This Is Us",
                    "The Good Place",
                    "BoJack Horseman",
                    "Money Heist",
                    "The Boys",
                    "The Expanse",
                    "The Haunting of Hill House",
                    "Outlander",
                    "Dark",
                    "Ozark",
                    "The Umbrella Academy",
                    "Cobra Kai",
                    "Altered Carbon",
                    "The Mandalorian",
                    "The Witcher",
                    "Every Body Hate Chris",
                    "The Fresh Prince of Bel-Air",
                    "The Nanny",
                    "The Golden"
                ]
            },            
            {
                code: 11,
                title: 'Famous People',
                theme: 'Famous People',
                words: [
                    "Albert Einstein",
                    "Leonardo da Vinci",
                    "Martin Luther King Jr.",
                    "Nelson Mandela",
                    "Mahatma Gandhi",
                    "Abraham Lincoln",
                    "Steve Jobs",
                    "Elon Musk",
                    "Oprah Winfrey",
                    "Michael Jordan",
                    "Serena Williams",
                    "David Beckham",
                    "Beyoncé",
                    "Taylor Swift",
                    "Marilyn Monroe",
                    "Leonardo DiCaprio",
                    "Tom Hanks",
                    "Angelina Jolie",
                    "Emma Watson",
                    "Kanye West",
                    "Ellen DeGeneres",
                    "Stephen Hawking",
                    "J.K. Rowling",
                    "Barack Obama",
                    "Queen Elizabeth II",
                    "Winston Churchill",
                    "Pablo Picasso",
                    "Vincent van Gogh",
                    "Amelia Earhart",
                    "Muhammad Ali",
                    "Pele",
                    "Marie Curie",
                    "Bill Gates",
                    "Mark Zuckerberg",
                    "Malala Yousafzai",
                    "Rosa Parks",
                    "Walt Disney",
                    "Steve Irwin",
                    "Princess Diana",
                    "Alexander Graham Bell",
                    "Coco Chanel",
                    "Ernest Hemingway",
                    "Frida Kahlo",
                    "Neil Armstrong",
                    "Elvis Presley",
                    "Bob Marley",
                    "Michael Jackson",
                    "John Lennon",
                    "Freddie Mercury",
                    
                ]
            },
            {
                code: 12,
                title: 'Video Games',
                theme: 'Video Games',
                words: [
                    "The Legend of Zelda",
                    "Super Mario Bros.",
                    "Pokémon",
                    "Final Fantasy",
                    "Halo",
                    "Call of Duty",
                    "Fortnite",
                    "Minecraft",
                    "Grand Theft Auto",
                    "Overwatch",
                    "League of Legends",
                    "World of Warcraft",
                    "The Elder Scrolls",
                    "Metal Gear Solid",
                    "Uncharted",
                    "Resident Evil",
                    "Assassin's Creed",
                    "Super Smash Bros.",
                    "Fallout",
                    "Red Dead Redemption",
                    "Dark Souls",
                    "The Witcher",
                    "God of War",
                    "Destiny",
                    "Street Fighter",
                    "Mortal Kombat",
                    "FIFA",
                    "NBA 2K",
                    "Animal Crossing",
                    "Splatoon",
                    "Doom",
                    "Counter-Strike",
                    "Half-Life",
                    "The Sims",
                    "Diablo",
                    "StarCraft",
                    "Borderlands",
                    "Portal",
                    "Mass Effect",
                    "Rocket League",
                    "Fortnite",
                    "Among Us",
                    "Cyberpunk 2077",
                    "Valorant",
                    "Apex Legends",
                    "Genshin Impact",
                    "The Last of Us",
                    "Mario Kart",                    
                    "Donkey Kong",
                    "Bomberman",
                    "Sonic the Hedgehog",
                ]
            },
            {
                code: 13,
                title: 'Pokemons',
                theme: 'Pokemons',
                words: [
                    "Pikachu",
                    "Charizard",
                    "Bulbasaur",
                    "Squirtle",
                    "Jigglypuff",
                    "Mewtwo",
                    "Eevee",
                    "Snorlax",
                    "Gyarados",
                    "Dragonite",
                    "Mew",
                    "Gengar",
                    "Magikarp",
                    "Psyduck",
                    "Vaporeon",
                    "Flareon",
                    "Jolteon",
                    "Gardevoir",
                    "Lucario",
                    "Lugia",
                    "Ho-Oh",
                    "Rayquaza",
                    "Groudon",
                    "Kyogre",
                    "Celebi",
                    "Greninja",
                    "Charmander",
                    "Blastoise",
                    "Venusaur",
                    "Raichu",
                    "Zapdos",
                    "Articuno",
                    "Moltres",
                    "Suicune",
                    "Entei",
                    "Raikou",
                    "Lapras",
                    "Gengar",
                    "Alakazam",
                    "Arcanine",
                    "Pidgeot",
                    "Sceptile",
                    "Gardevoir",
                    "Swampert",
                    "Blaziken",
                    "Gallade",
                    "Garchomp"
                ]
            },
            {
                code: 14,
                title: 'Brazilians',
                theme: 'Bagulhos do Brasil',
                words: [
                    "Samba",
                    "Carnaval",
                    "Rio de Janeiro",
                    "São Paulo",
                    "Brasília",
                    "Amazon Rainforest",
                    "Ipanema",
                    "Capoeira",
                    "Feijoada",
                    "Açaí",
                    "Caipirinha",
                    "Pelé",
                    "Ronaldinho",
                    "Neymar",
                    "Gisele Bündchen",
                    "Oscar Niemeyer",
                    "Cristo Redentor",
                    "Fernando de Noronha",
                    "Pantanal",
                    "Favela",
                    "Tropicalismo",
                    "Jorge Amado",
                    "Vinicius de Moraes",
                    "Tom Jobim",
                    "Gilberto Gil",
                    "Carmen Miranda",
                    "Churrasco",
                    "Bossa Nova",
                    "Cangaço",
                    "Telenovela",
                    "Cachaça",
                    "Maracanã",
                    "Paraty",
                    "Porto de Galinhas",
                    "Salvador",
                    "Ouro Preto",
                    "Tiradentes",
                    "Recife",
                    "Bahia",
                    "Pão de Açúcar",
                    "Copacabana",
                    "Anitta",
                    "Jair Bolsonaro",
                    "Ayrton Senna",
                    "Gabriela Mistral",
                    "Carlos Drummond de Andrade",
                    "Machado de Assis",
                    "Clarice Lispector",
                    "Tarsila do Amaral",
                    "Oswald de Andrade",
                    "Heitor Villa-Lobos",
                    "Carmen Miranda",
                    "Chico Buarque",
                    "Caetano Veloso",
                    "Dilma Rousseff",
                    "Fernando Henrique Cardoso",
                    "Luiz Inácio Lula da Silva",
                    "Jair Bolsonaro",
                    "Cunbica",
                    "Carnaval",
                    "Mula Sem Cabeça",
                    "Boitatá",
                    "Sapo Cururu",
                    "Curupira",
                    "Dedo no Cu e gritaria",
                    "Pau de Selfie",
                    "Pão de Queijo",
                    "Coxinha",
                    "Brigadeiro",
                    "Pão na Chapa",
                    "Pastel de Feira", 
                    "Cachorro Caramelo",                  

                ]
            },
            {
                code: 15,
                title: 'Brazilian Movies and TV Shows',
                theme: 'Brazilian Movies and TV Shows',
                words: [
                    "City of God (Cidade de Deus)",
                    "Central Station (Central do Brasil)",
                    "Elite Squad (Tropa de Elite)",
                    "The Two Popes (Dois Papas)",
                    "Bacurau",
                    "Aquarius",
                    "The Motorcycle Diaries (Diários de Motocicleta)",
                    "The Elite Squad 2: The Enemy Within (Tropa de Elite 2: O Inimigo Agora é Outro)",
                    "Brazil Avenue (Avenida Brasil)",
                    "Redeemer (O Mecanismo)",
                    "The Invisible Woman (A Mulher Invisível)",
                    "The Clown (O Palhaço)",
                    "My Hindu Friend (Meu Amigo Hindu)",
                    "Kiss of the Spider Woman (O Beijo da Mulher Aranha)",
                    "Four Days in September (O Que É Isso, Companheiro?)",
                    "Elite Squad: The Enemy Within (Tropa de Elite 2: O Inimigo Agora é Outro)",
                    "Viva Voz",
                    "Tropical Paradise (Paraíso Tropical)",
                    "Me, You, Them (Eu, Tu, Eles)",
                    "The Year My Parents Went on Vacation (O Ano em Que Meus Pais Saíram de Férias)",
                    "The Tenants (Os Inquilinos)",
                    "Aquarius",
                    "The Second Mother (Que Horas Ela Volta?)",
                    "Elite Squad (Tropa de Elite)",
                    "Good Morning, Verônica (Bom Dia, Verônica)",
                    "Shantytown (Cidade Baixa)",
                    "Carandiru",
                    "The King of the Cattle (O Rei do Gado)",
                    "The Clone (O Clone)",
                    "Burning Hearts (Fogo no Céu)",
                    "Favela Rising",
                    "The Invisible Woman (A Mulher Invisível)",
                    "Trash (Trash: A Esperança Vem do Lixo)",
                    "The Man from the Future (O Homem do Futuro)",
                    "Me You Them (Eu, Tu, Eles)",
                    "Wild Tales (Relatos Selvagens)",
                    "Narcos",                    
                    "The Edge of Democracy (Democracia em Vertigem)",
                    "Girl from Ipanema (Coisa Mais Linda)",
                    "Chaves",
                    "Carrossel",
                    "A Grande Família",
                    "Sítio do Picapau Amarelo",
                    "Casseta & Planeta",
                    "Os Normais",
                    "Castelo Rá-Tim-Bum",
                    "A Diarista",
                    "Chapolin Colorado",
                    "TV Colosso",
                    "Xuxa",
                ]
            },
            {
                code: 16,
                title: "Sports",
                theme: "Sports",
                words: [
                    "Soccer",
                    "Basketball",
                    "Tennis",
                    "Golf",
                    "Swimming",
                    "Running",
                    "Boxing",
                    "Martial Arts",
                    "Cricket",
                    "Baseball",
                    "Ice Hockey",
                    "Cycling",
                    "Rugby",
                    "Gymnastics",
                    "Wrestling",
                    "Surfing",
                    "Skiing",
                    "Snowboarding",
                    "Volleyball",
                    "Badminton"
                ]
            },
            {
                code: 17,
                title: "Technology",
                theme: "Technology",
                words: [
                    "Computer",
                    "Smartphone",
                    "Tablet",
                    "Laptop",
                    "Internet",
                    "Software",
                    "Hardware",
                    "Artificial Intelligence",
                    "Virtual Reality",
                    "Augmented Reality",
                    "Robotics",
                    "Blockchain",
                    "Cybersecurity",
                    "Cloud Computing",
                    "Biotechnology",
                    "Drones",
                    "IoT (Internet of Things)",
                    "Machine Learning",
                    "3D Printing",
                    "Space Exploration"
                ]
            },
            {
                code: 18,
                title: "Music Genres",
                theme: "Music Genres",
                words: [
                    "Pop",
                    "Rock",
                    "Hip Hop",
                    "Jazz",
                    "Blues",
                    "Country",
                    "Classical",
                    "Electronic",
                    "Reggae",
                    "R&B",
                    "Folk",
                    "Metal",
                    "Punk",
                    "Salsa",
                    "K-Pop",
                    "EDM",
                    "Funk",
                    "Gospel",
                    "Indie",
                    "Opera"
                ]
            },
            {
                code: 19,
                title: "Colors",
                theme: "Colors",
                words: [
                    "Red",
                    "Blue",
                    "Green",
                    "Yellow",
                    "Orange",
                    "Purple",
                    "Pink",
                    "Black",
                    "White",
                    "Brown",
                    "Gray",
                    "Silver",
                    "Gold",
                    "Turquoise",
                    "Crimson",
                    "Magenta",
                    "Indigo",
                    "Lime",
                    "Maroon",
                    "Teal"
                ]
            }
        ];
    }

    static getSelectedCategories() {
        
        if (typeof window === 'undefined') return [];
        
        const selectedCategories = JSON.parse(localStorage.getItem('selected-categories')) || [];
        const allCategories = CategoriesService.getAllCategories();
        const selectedCategoriesData = [];

        for (let i = 0; i < selectedCategories.length; i++) {
            const categoryCode = selectedCategories[i];
            const categoryData = allCategories.find(category => category.code === categoryCode);
            if (categoryData) {
                selectedCategoriesData.push(categoryData);
            }
        }

        return selectedCategoriesData;
    }
}

export default CategoriesService;